# Generated by Django 4.2.1 on 2023-08-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0063_alter_employee_initializer_all_amount_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='id',
        ),
        migrations.AlterField(
            model_name='employees',
            name='Employement_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
