# Generated by Django 4.2.1 on 2023-08-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0064_remove_employees_id_alter_employees_employement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalary',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
